name: Build & Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      # ⬇️ On n’upload QUE les fichiers voulus
      - name: Upload build artifacts (filtered)
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: |
            dist/**/*-arm64.dmg
            dist/**/*-arm64.dmg.blockmap
            dist/**/*-x64.dmg
            dist/**/*-x64.dmg.blockmap
            dist/**/*.AppImage
            dist/**/*.exe
            dist/**/*.exe.blockmap
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      # (Optionnel) Vérifier ce qui sera publié
      - name: List files to be released
        run: |
          echo "Files to upload:"
          ls -lh artifacts || true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-${{ github.run_number }}
          name: "Auto Release ${{ github.run_number }}"
          generate_release_notes: true
          files: |
            artifacts/**/*-arm64.dmg
            artifacts/**/*-arm64.dmg.blockmap
            artifacts/**/*-x64.dmg
            artifacts/**/*-x64.dmg.blockmap
            artifacts/**/*.AppImage
            artifacts/**/*.exe
            artifacts/**/*.exe.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
